import { Dimensions, StyleSheet } from "react-native";

const { height } = Dimensions.get('window');

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fdfdff', 
    paddingHorizontal: 20,
    paddingTop: 50, 
  },
  logo: {
    width: 60,
    height: 50,
  },
  boxTop: {
    width: '100%',
    marginBottom: 25,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignItems: 'center',
  },
  headerDate: {
    color: "#05021f86",
    fontSize: 11,
    fontWeight: 'bold',
  },
  headerGreeting: {
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 5,
  },
  boxMid: {
    width: '100%',
    backgroundColor: '#888EEF', 
    borderRadius: 20,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  saldoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  text: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 1,
    opacity: 0.8,
  },
  saldoValor: {
    fontSize: 32,
    color: '#FFF',
    fontWeight: '900',
    marginTop: 10,
  },
  resumoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    width: '100%',
  },
  blocoEntrada: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    padding: 12,
    borderRadius: 12,
    width: '48%',
  },
  blocoSaida: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    padding: 12,
    borderRadius: 12,
    width: '48%',
  },
  blocoIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  blocoLabelEntrada: {
    color: '#00f829',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  blocoLabelSaida: {
    color: '#e02914',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  blocoValor: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  btnNovaTransacao: {
    backgroundColor: '#888EEF', 
    padding: 16,
    borderRadius: 15,
    marginTop: 20,
    alignItems: 'center',
    width: '100%',
  },
  btnNovaTransacaoText: {
    color: '#FFF',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  cardContainer: {
    backgroundColor: '#FAF5EF',
    borderRadius: 24,
    padding: 20,
    width: '100%',
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#EFEAE2',
  },
  subtitle: {
    fontSize: 11,
    color: '#8A857F',
    letterSpacing: 1.5,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  mainRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  streakNumber: {
    fontSize: 48,
    fontWeight: '900',
    color: '#E87722',
    lineHeight: 48,
  },
  streakText: {
    fontSize: 28,
    fontWeight: '900',
    color: '#E87722',
    lineHeight: 28,
  },
  streakQuebradoColor: {
    color: '#8A857F',
  },
  fireGroup: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  fireRow: {
    flexDirection: 'row',
  },
  fireLeftMargin: {
    marginRight: -5,
  },
  singleFire: {
    marginTop: -8,
  },
  statusText: {
    fontSize: 14,
    color: '#605C57',
    marginTop: 10,
  },
  boldStatus: {
    fontWeight: 'bold',
    color: '#403D39',
  },
  dashContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
    marginBottom: 5,
    width: '100%',
  },
  dashActive: {
    flex: 1,
    height: 5,
    backgroundColor: '#E87722',
    borderRadius: 2.5,
    marginHorizontal: 3,
  },
  dashInativoBg: {
    backgroundColor: '#D3D3D3',
  },
  footerText: {
    fontSize: 11,
    color: '#A09B95',
    marginTop: 2,
  },
  historicoContainer: {
    backgroundColor: '#FFF',
    marginTop: 20,
    borderRadius: 25,
    padding: 20,
    width: '100%',
    marginBottom: 40,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 3,
  },
  historicoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
  },
  historicoTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#222',
  },
  btnVerTodas: {
    color: '#2F7D5B',
    fontWeight: 'bold',
    fontSize: 14,
  },
  itemTransacao: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 22,
    width: '100%',
  },
  itemTransacaoInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemIconBox: {
    width: 45,
    height: 45,
    borderRadius: 14,
    backgroundColor: '#F3F3F3',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  itemTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#222',
  },
  itemSub: {
    color: '#999',
    fontSize: 13,
    marginTop: 2,
  },
  itemValor: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalKeyboardContainer: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: '#FFF',
    padding: 25,
    borderRadius: 25,
    width: '100%',
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  modalTipoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    width: '100%',
  },
  btnSeletorTipo: {
    padding: 12,
    borderWidth: 2,
    borderRadius: 12,
    width: '48%',
    alignItems: 'center',
  },
  btnSeletorEntrada: {
    borderColor: '#EEE',
  },
  btnSeletorEntradaAtivo: {
    borderColor: '#2F7D5B',
  },
  btnSeletorSaida: {
    borderColor: '#EEE',
  },
  btnSeletorSaidaAtivo: {
    borderColor: '#C62828',
  },
  btnSeletorText: {
    fontWeight: 'bold',
  },
  modalInput: {
    backgroundColor: '#F5F5F5',
    padding: 15,
    borderRadius: 12,
    fontSize: 22,
    marginBottom: 20,
    textAlign: 'center',
    fontWeight: 'bold',
    width: '100%',
  },
  btnConfirmar: {
    backgroundColor: '#888EEF',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 10,
    width: '100%',
  },
  btnConfirmarText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  btnCancelar: {
    padding: 10,
    width: '100%',
  },
  btnCancelarText: {
    color: '#999',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  boxBottom: {
    width: '100%',
    marginTop: 20,
    padding: 10,
  },
});